apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: test
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: ghcr.io/giorgosdi/test:v0.1
        imagePullPolicy: IfNotPresent
        name: test
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: database-configs
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-configs
  namespace: test
data:
  PORT: "8080"
  POSTGRESQL_HOST: "giorgos-infra-master.cvv5huvqatav.eu-west-2.rds.amazonaws.com"
  POSTGRESQL_PORT: "5432"
  POSTGRESQL_DBNAME: replicaPostgresql
  POSTGRESQL_USER: replica_postgresql
  POSTGRESQL_PASSWORD: "kldN02vpsieOuLoZ"
