apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: ghcr.io/giorgosdi/test:latest
        imagePullPolicy: Always
        name: test
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: database-configs
        env:
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: postgres-password
        # this is necessary for autoscaling
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-configs
  namespace: test
data:
  PORT: "8080"
  POSTGRESQL_HOST: postgresql.test.svc.cluster.local
  POSTGRESQL_PORT: "5432"
  POSTGRESQL_DBNAME: replicaPostgresql
  POSTGRESQL_USER: replica_postgresql
  POSTGRESQL_PASSWORD: 12345
